import type { ParkingLot } from "@/types/parking";

export const mockParkingLots: ParkingLot[] = [
  {
    id: "kremlin",
    owner_id: "owner1",
    name: "ParkEase у Кремля",
    description: "Парковка рядом с центром города",
    address: "Манежная площадь, Москва",
    latitude: 55.752,
    longitude: 37.6175,
    total_spots: 50,
    price_per_hour: 200,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "europeisky",
    owner_id: "owner1",
    name: "Парковка ТЦ Европейский",
    description: "Крытая парковка у торгового центра",
    address: "Площадь Киевского Вокзала, 2",
    latitude: 55.7449,
    longitude: 37.5652,
    total_spots: 120,
    price_per_hour: 150,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "tverskaya",
    owner_id: "owner1",
    name: "Гараж на Тверской",
    description: "Компактный городской гараж",
    address: "Тверская улица, Москва",
    latitude: 55.765,
    longitude: 37.6058,
    total_spots: 30,
    price_per_hour: 300,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "vdnh",
    owner_id: "owner2",
    name: "Парковка ВДНХ",
    description: "Большая открытая парковка",
    address: "Проспект Мира, 119",
    latitude: 55.8263,
    longitude: 37.6376,
    total_spots: 200,
    price_per_hour: 80,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "arbat",
    owner_id: "owner2",
    name: "Подземная у Арбата",
    description: "Подземная охраняемая парковка",
    address: "Новый Арбат, Москва",
    latitude: 55.7522,
    longitude: 37.5876,
    total_spots: 45,
    price_per_hour: 250,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
